import type { AppointmentRow } from "../../models/appointmentModel.js";

export const formatAppointment = (appointment: AppointmentRow) => ({
    id: appointment.id,
    customerId: appointment.customer_id,
    employeeId: appointment.employee_id,
    serviceId: appointment.service_id,
    appointmentDate: appointment.appointment_date,
    startTime: appointment.start_time,
    endTime: appointment.end_time,
    totalAmount: Number(appointment.total_amount),
    notes: appointment.notes,
    status: appointment.status,
    startedAt: appointment.started_at,
    completedAt: appointment.completed_at,
    cancelledAt: appointment.cancelled_at,
    cancellationReason: appointment.cancellation_reason,
    customerName: appointment.customer_name,
    customerPhone: appointment.customer_phone,
    customerEmail: appointment.customer_email,
    employeeName: appointment.employee_name,
    serviceName: appointment.service_name,
    serviceDurationMinutes: appointment.service_duration_minutes,
    createdAt: appointment.created_at,
    updatedAt: appointment.updated_at,
});
